-- ============================================================
-- SEED DATA — Migrasi 56 data baseline dari dashboard HTML lama
-- Jalankan SEKALI saja setelah schema.sql berhasil dibuat.
-- ============================================================

insert into kecelakaan (tgl, nama, subdep, jenis, kronologi, lokasi, hko) values
  ('2026-01-19', 'Rahmad Tullah', 'Processing Cannery', 'Tersayat', 'Membersihkan crown tersangkut di pisau crown, tangan kiri jempol tersayat pisau', 'Area Ginaca 08', 0),
  ('2026-01-20', 'Fedelis Beni Santoso', 'Non Can', 'Tergores', 'Memperbaiki mesin pengering dengan boor tangan, boor meleset kena jari jempol kiri', 'Laundry sarung tangan', 0),
  ('2026-01-24', 'Ida Natalia', 'Processing Cannery', 'Terpeleset/Terjatuh', 'Membawa selang melewati area cooker, terpeleset ceceran soda api di lantai', 'Samping cooker depan ruang mekanik', 0),
  ('2026-01-31', 'Farida', 'Processing Cannery', 'Paparan Kimia/Soda', 'Cuci mesin menyikat talang SKS, soda api tidak sengaja mengenai mata dan leher', 'Area SKS potong bonggol line 24', 0),
  ('2026-01-31', 'Jumiati', 'Processing Cannery', 'Paparan Kimia/Soda', 'Cuci mesin menyemprot soda api ke MTC 013, percikan soda api mengenai mata kanan', 'Area MTC 013', 0.5),
  ('2026-02-05', 'Ani Listyarin', 'Quality Control', 'Tertimpa Benda', 'Tray 12x20oz terjatuh dari mesin paletizer mengenai kepala korban saat inspeksi line 8', 'Line 8 labelling factory', 0),
  ('2026-02-05', 'Rangga Bramantya', 'Labelling', 'Paparan Kimia/Soda', 'Aktivitas perbaikan mesin menggunakan alat las, mata terpapar asap las', 'Label', 0),
  ('2026-02-07', 'Winarni', 'Processing Cannery', 'Terkilir', 'Mengambil nampan dengan kereta dorong, saat membelokkan kereta dorong pinggang terkilir', 'Area line 16', 0),
  ('2026-02-13', 'Hadi Iswanto', 'Processing Cannery', 'Tertusuk', 'Mengukur mika menggunakan profil aluminium, jari telunjuk tangan kiri tertusuk profil', 'Workshop PPBP cannery', 0),
  ('2026-02-13', 'Komsiyah', 'Processing Cannery', 'Terpeleset/Terjatuh', 'Turun dari dak terpeleset dan jatuh posisi duduk, kepala terbentur meja, siku tangan kanan kena tiang meja', 'Area CTB 04', 1),
  ('2026-02-28', 'Meri Yusnita', 'Processing Cannery', 'Paparan Kimia/Soda', 'Cuci mesin menyikat lantai line VI menggunakan soda api, terpercik mengenai mata kanan', 'Area Line 06', 0),
  ('2026-03-03', 'Zainal Abidin', 'Labelling', 'Terpeleset/Terjatuh', 'Berangkat kerja dengan sepeda motor, mengerem mendadak, ban motor tergelincir dan terjatuh', 'Area label', 0),
  ('2026-03-06', 'Yulia Melda Sari', 'Processing Cannery', 'Terpeleset/Terjatuh', 'Diperbantukan di GN, saat naik tangga GN 17 terpeleset dan terjatuh, kepala terbentur lantai', 'Area RM GN 17', 3),
  ('2026-03-06', 'Widori Ningsih', 'Processing Cannery', 'Terpeleset/Terjatuh', 'Mendorong gerobak tutup kaleng, terpeleset karena terlalu berat, lutut kiri berbunyi dan nyeri', 'Area Mesin SA 01', 2),
  ('2026-03-09', 'Adi Purnawijaya', 'Maintenance Cannery', 'Terjepit', 'Memperbaiki mesin seamer, saat mengambil tutup kaleng terjepit mengenai jari manis tangan kiri', 'Area Seamer 5508', 0),
  ('2026-03-09', 'Fajar Nur Hidayat', 'Maintenance Cannery', 'Tersayat/Tergores', 'Menyiapkan alat sambung conveyor, tangan tidak sengaja menyandar ke baling-baling berputar', 'Ruang Perubahan produksi Maintenance Cannery', 0),
  ('2026-03-09', 'Palupi Yenita Maria', 'Labelling', 'Tertimpa Benda', 'Aktivitas proses loading barang, kaki kiri tertimpa/tertekan lidah forklift', 'Area label', 2),
  ('2026-03-11', 'Ngatmi', 'Processing Cannery', 'Terjepit', 'Menutup mesin cutting, pegangan lepas dan menimpa tangan kiri, jari tengah patah dan jari manis luka', 'Mesin cutting Line 13', 2),
  ('2026-03-24', 'Taufik Hidayat', 'Maintenance Cannery', 'Paparan Kimia/Soda', 'Aktivitas service mesin, duduk di area cuci mesin rekan kerja, terkena cairan soda pada paha belakang kiri', 'Line 11', 0),
  ('2026-03-30', 'Sujianto', 'Labelling', 'Terjepit', 'Menggantikan operator mesin Palletizer Line 11, mengarahkan produk, jari telunjuk kanan terjepit di antara 2 produk karton', 'Paletizer Line 11 Label', 0),
  ('2026-04-01', 'Suprihantoro', 'Processing Cannery', 'Terjepit', 'Mendorong gerobak tutup, saat belok menabrak tiang, gerobak mundur dan jari kelingking kanan terjepit tangki cooker seamer', 'Lokasi pengisian END (tutup)', 0),
  ('2026-04-06', 'Hayuna', 'Processing Cannery', 'Tertimpa Benda', 'Menimbang CR A10, kaleng numpuk mengalir terus karena operator tidak mendengar instruksi stop, kaleng mengenai kaki', 'SAS 09', 0),
  ('2026-04-07', 'Liswiyanti', 'Processing Cannery', 'Tersayat', 'Saat memotong bonggol, jari telunjuk tangan kiri tersayat pisau', 'Area Potong Bonggol', 0),
  ('2026-04-21', 'Erma Erpiyana', 'Processing Cannery', 'Tergores', 'Mengisi nanas can A10, can hendak jatuh, reflek menahan can sehingga jari tengah tangan kiri tergores', 'Line 12', 0),
  ('2026-04-23', 'Andre Rakasiwi', 'QA Factory', 'Terjepit', 'Membantu menutup pintu gudang karton, jari tangan berada di celah engsel saat pintu didorong, jari tengah kiri luka', 'Gudang Karton Labeling', 0),
  ('2026-04-26', 'Arif Triono', 'Processing Cannery', 'Paparan Kimia/Soda', 'Beraktivitas mengecat di area raw material, percikan cairan hypo dari geliden yang tidak tertutup mengenai mata kanan', 'RM, GN', 0),
  ('2026-04-27', 'Nuraini', 'Processing Cannery', 'Paparan Kimia/Soda', 'Piket menyiram body mesin dengan soda api yang diencerkan, tidak sengaja mata kiri kecipratan soda api', 'SAS 03', 0),
  ('2026-04-27', 'Parida Yulia', 'Processing Cannery', 'Paparan Kimia/Soda', 'Menyeleksi material nanas, sarung tangan bocor, tangan kiri terkena air nanas mengakibatkan iritasi', 'CYR 01', 0),
  ('2026-04-28', 'Intan Oktaviani', 'Processing Cannery', 'Tersayat', 'Cuci mesin awal, menyikat area cross, antara ibu jari dan telunjuk tersayat plat cross hingga robek', 'Area CTB dan Line 11', 0),
  ('2026-05-04', 'Masnuning', 'Processing Cannery', 'Lain-lain', 'Akan menaiki tangga, lutut kaki kanan terasa nyeri dan bengkak, sulit digerakkan', 'Area potong bonggol line 15', 1),
  ('2026-05-06', 'Camilia Safitri', 'Processing Cannery', 'Terjepit', 'Membersihkan mesin RZR line 7, tiba-tiba mesin push bar hidup dan terkena jari tangan kiri', 'Area mesin RZR di line 7', 0),
  ('2026-05-07', 'Didik Santoso', 'MC Cannery', 'Paparan Kimia/Soda', 'Menggerinda tutup rantai, terkena percikan gram/serpihan pada mata kanan', 'Raw material', 0),
  ('2026-05-11', 'Media Natalina', 'Processing Cannery', 'Terjepit', 'Mengoperasikan mesin, jari terjepit di antara dudukan pisau crown dan buah di elevator', 'Ginaca 03', 0),
  ('2026-05-11', 'Merwanda', 'PPIC support', 'Paparan Kimia/Soda', 'Menggerinda mata pisau potong rumput, tidak sengaja mata kiri terkena percikan gram', 'Belakang Mill Juice', 0),
  ('2026-05-12', 'Mariah', 'Processing Cannery', 'Terpeleset/Terjatuh', 'Berjalan di lokasi line 23, terpeleset karena sepatu licin kemudian terjatuh, bibir atas robek', 'Area line 23', 0.5),
  ('2026-05-14', 'Lia Asmarani', 'Processing Cannery', 'Terjepit', 'Mengoper produk di jalur MTC line 5, produk roboh, saat membetulkan produk jari tangan terjepit jalur MTC', 'Area MTC line 05', 1),
  ('2026-05-17', 'Wasilah', 'Processing Cannery', 'Paparan Kimia/Soda', 'Menyikat baskom yang diaplikasi soda api, tidak sengaja mata kiri terkena cipratan soda api', 'Bak pencucian nampan line 22', 0),
  ('2026-05-17', 'Happy Mahoyani', 'Processing Cannery', 'Paparan Kimia/Soda', 'Mencuci nampan dengan soda api, sisa soda api di gayung menetes mengenai paha kanan — luka bakar', 'Area line 13', 0),
  ('2026-05-17', 'Maria Andriyani', 'Processing Cannery', 'Terpeleset/Terjatuh', 'Mendorong produk dari CTB 06, lantai licin sehingga terpeleset dengan posisi terduduk, pinggang nyeri', 'Antara line 6 dan 7', 0),
  ('2026-05-19', 'Susi Andika', 'Processing Cannery', 'Tertimpa Benda', 'Menyusun produk kaleng A10 di line 14, produk jatuh mengenai jari kelingking dan tergores', 'Line 14', 0.5),
  ('2026-05-22', 'Musa', 'MC Cannery', 'Terkilir', 'Melakukan pengelasan dengan posisi berdiri, punggung kiri keseleo dan urat ketarik', 'Aseptik', 0),
  ('2026-05-24', 'Danang Eka Prasetya', 'Processing Cannery', 'Terjepit', 'Memasukkan gerobak tutup ke SAS 08, tutup gerobak nabrak tiang, menghimpit jari tangan kanan — luka sobek', 'SAS 08', 0.5),
  ('2026-05-28', 'Rumiatun', 'Processing Cannery', 'Terpeleset/Terjatuh', 'Menaiki podium line 22, kaki kiri terpeleset dan jatuh terguling ke lantai, pantat kiri nyeri', 'Podium Line 22', 0),
  ('2026-05-29', 'Irma Nur Prihatini', 'Processing Cannery', 'Tersayat', 'Membuang biji jambu menggunakan pisau, jari kelingking tangan kiri tersayat pisau', 'Pengupasan TFS', 1),
  ('2026-06-03', 'Agung Marute Gusman', 'Raw Material', 'Lain-lain', 'Saat menutup Bin, mata terkena serpihan besi tutup bin', 'Tempat buka tutup Bin (RM)', 0),
  ('2026-06-03', 'Arya Dwi Permana', 'Power Plant', 'Paparan Kimia/Soda', 'Sedang bekerja gerinda poles, tidak sengaja mata kiri terkena percikan gerinda', 'Boiler', 0),
  ('2026-06-03', 'Benny Alvandi', 'Maintenance Cannery', 'Paparan Kimia/Soda', 'Saat ngetak las besi rantai, bekas las/tai las mental masuk ke dalam mata kiri', 'Raw Material', 0),
  ('2026-06-04', 'Heny Dwi Safira', 'Processing Cannery', 'Terpeleset/Terjatuh', 'Saat mengangkat nampan CR ke mesin RZR line 12, terpeleset dan kepala tertimpa nampan, sempat pingsan — kening benjol dan nyeri, lutut kaki kiri memar kebiruan', 'Area potong bonggol Line 12', 0),
  ('2026-06-10', 'Dzakwan Arhab Heliyanja', 'Can Making', 'Terjepit', 'Saat hendak wrapping end di palet, wrapping turun sendiri dan tangan kiri terjepit — luka dan hematom pada tangan kiri', 'Can making end line', 0),
  ('2026-06-10', 'Saihu', 'Processing Cannery', 'Terpeleset/Terjatuh', 'Saat naik ke screw aseptic hampir terjatuh terpeleset, kaki terbentur anak tangga — memar di kaki kanan', 'Tangga aseptic', 0),
  ('2026-06-11', 'Mariono', 'Factory Keeping', 'Tertusuk', 'Saat service palet/dongkel palet, ada papan terpental ada pakunya. Saat meletakkan papan palet afkir ke box/ram, tidak sengaja menginjak paku yang menembus sepatu safety boot — luka tusuk telapak kaki kiri', 'Service Palet', 0),
  ('2026-06-11', 'Eliya', 'Processing Cannery', 'Terjepit', 'Saat bantu SM 01 memperbaiki can yang roboh di Top can, ada TK SM yang menekan tombol liter can dan kaki terjepit', 'SM 01', 0),
  ('2026-06-13', 'Aggung Setiyadi', 'Maintenance Cannery', 'Terpeleset/Terjatuh', 'Saat perbaikan mesin cooker LTC5504, berjalan di samping tangga sebelah parit, terpeleset dan kaki kanan masuk parit berisi air panas — luka bakar di pergelangan kaki kanan, melepuh dan merah', 'LTC5504', 0),
  ('2026-06-13', 'Sumarsono', 'Label', 'Tertimpa Benda', 'Saat mengendarai forklift hendak belok namun lurus lalu mengerem mendadak, palet jatuh ke arah muka, saat melindungi muka dengan tangan jari telunjuk kanan tertimpa palet — luka amputatum jari telunjuk tangan kanan', 'Gudang baru blok J', 3),
  ('2026-06-14', 'Nuryana', 'SCN', 'Paparan Kimia/Soda', 'Menuangkan soda api dari ember ke gayung atas permintaan TK line VII, tidak sengaja bibir terciprat soda api — bibir bengkak dan terasa tebal', 'Gudang 01', 0),
  ('2026-06-19', 'Najamudin', 'Power Plant', 'Tertimpa Benda', 'Pada saat tenaga kerja melakukan kegiatan 5R (Ringkas, Rapi, Resik, Rawat, Rajin) di area kerja ESP #03, yang bersangkutan tidak menggunakan alat pelindung diri (APD) berupa safety helmet. Saat proses pembersihan berlangsung, tenaga kerja menarik selang air untuk menyiram lantai kerja. Selang tersebut tersangkut atau terkait dengan pipa besi yang disandarkan di area unit telescope. Akibat tarikan tersebut, pipa besi ikut tertarik dan kemudian jatuh menimpa tenaga kerja. Pipa besi tersebut merupakan alat kerja yang digunakan untuk mengatasi fly ash yang terjebak di dalam saluran telescope.', 'ESP #03', 3);